name: My first Ci
on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean install

